# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shestopalovy/Projects/GodBot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shestopalovy/Projects/GodBot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shestopalovy/Projects/GodBot/CMakeFiles /home/shestopalovy/Projects/GodBot//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shestopalovy/Projects/GodBot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named godbot

# Build rule for target.
godbot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 godbot
.PHONY : godbot

# fast build rule for target.
godbot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/build
.PHONY : godbot/fast

src/GB_LogData.o: src/GB_LogData.cpp.o
.PHONY : src/GB_LogData.o

# target to build an object file
src/GB_LogData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_LogData.cpp.o
.PHONY : src/GB_LogData.cpp.o

src/GB_LogData.i: src/GB_LogData.cpp.i
.PHONY : src/GB_LogData.i

# target to preprocess a source file
src/GB_LogData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_LogData.cpp.i
.PHONY : src/GB_LogData.cpp.i

src/GB_LogData.s: src/GB_LogData.cpp.s
.PHONY : src/GB_LogData.s

# target to generate assembly for a file
src/GB_LogData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_LogData.cpp.s
.PHONY : src/GB_LogData.cpp.s

src/GB_Logger.o: src/GB_Logger.cpp.o
.PHONY : src/GB_Logger.o

# target to build an object file
src/GB_Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_Logger.cpp.o
.PHONY : src/GB_Logger.cpp.o

src/GB_Logger.i: src/GB_Logger.cpp.i
.PHONY : src/GB_Logger.i

# target to preprocess a source file
src/GB_Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_Logger.cpp.i
.PHONY : src/GB_Logger.cpp.i

src/GB_Logger.s: src/GB_Logger.cpp.s
.PHONY : src/GB_Logger.s

# target to generate assembly for a file
src/GB_Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_Logger.cpp.s
.PHONY : src/GB_Logger.cpp.s

src/GB_SimpleStrategy.o: src/GB_SimpleStrategy.cpp.o
.PHONY : src/GB_SimpleStrategy.o

# target to build an object file
src/GB_SimpleStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_SimpleStrategy.cpp.o
.PHONY : src/GB_SimpleStrategy.cpp.o

src/GB_SimpleStrategy.i: src/GB_SimpleStrategy.cpp.i
.PHONY : src/GB_SimpleStrategy.i

# target to preprocess a source file
src/GB_SimpleStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_SimpleStrategy.cpp.i
.PHONY : src/GB_SimpleStrategy.cpp.i

src/GB_SimpleStrategy.s: src/GB_SimpleStrategy.cpp.s
.PHONY : src/GB_SimpleStrategy.s

# target to generate assembly for a file
src/GB_SimpleStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GB_SimpleStrategy.cpp.s
.PHONY : src/GB_SimpleStrategy.cpp.s

src/GodBot.o: src/GodBot.cpp.o
.PHONY : src/GodBot.o

# target to build an object file
src/GodBot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GodBot.cpp.o
.PHONY : src/GodBot.cpp.o

src/GodBot.i: src/GodBot.cpp.i
.PHONY : src/GodBot.i

# target to preprocess a source file
src/GodBot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GodBot.cpp.i
.PHONY : src/GodBot.cpp.i

src/GodBot.s: src/GodBot.cpp.s
.PHONY : src/GodBot.s

# target to generate assembly for a file
src/GodBot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/GodBot.cpp.s
.PHONY : src/GodBot.cpp.s

src/Kline.o: src/Kline.cpp.o
.PHONY : src/Kline.o

# target to build an object file
src/Kline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/Kline.cpp.o
.PHONY : src/Kline.cpp.o

src/Kline.i: src/Kline.cpp.i
.PHONY : src/Kline.i

# target to preprocess a source file
src/Kline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/Kline.cpp.i
.PHONY : src/Kline.cpp.i

src/Kline.s: src/Kline.cpp.s
.PHONY : src/Kline.s

# target to generate assembly for a file
src/Kline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/Kline.cpp.s
.PHONY : src/Kline.cpp.s

src/base_api.o: src/base_api.cpp.o
.PHONY : src/base_api.o

# target to build an object file
src/base_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/base_api.cpp.o
.PHONY : src/base_api.cpp.o

src/base_api.i: src/base_api.cpp.i
.PHONY : src/base_api.i

# target to preprocess a source file
src/base_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/base_api.cpp.i
.PHONY : src/base_api.cpp.i

src/base_api.s: src/base_api.cpp.s
.PHONY : src/base_api.s

# target to generate assembly for a file
src/base_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/base_api.cpp.s
.PHONY : src/base_api.cpp.s

src/binance_api.o: src/binance_api.cpp.o
.PHONY : src/binance_api.o

# target to build an object file
src/binance_api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/binance_api.cpp.o
.PHONY : src/binance_api.cpp.o

src/binance_api.i: src/binance_api.cpp.i
.PHONY : src/binance_api.i

# target to preprocess a source file
src/binance_api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/binance_api.cpp.i
.PHONY : src/binance_api.cpp.i

src/binance_api.s: src/binance_api.cpp.s
.PHONY : src/binance_api.s

# target to generate assembly for a file
src/binance_api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/binance_api.cpp.s
.PHONY : src/binance_api.cpp.s

src/curl_object.o: src/curl_object.cpp.o
.PHONY : src/curl_object.o

# target to build an object file
src/curl_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/curl_object.cpp.o
.PHONY : src/curl_object.cpp.o

src/curl_object.i: src/curl_object.cpp.i
.PHONY : src/curl_object.i

# target to preprocess a source file
src/curl_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/curl_object.cpp.i
.PHONY : src/curl_object.cpp.i

src/curl_object.s: src/curl_object.cpp.s
.PHONY : src/curl_object.s

# target to generate assembly for a file
src/curl_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/curl_object.cpp.s
.PHONY : src/curl_object.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/godbot.dir/build.make CMakeFiles/godbot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... godbot"
	@echo "... src/GB_LogData.o"
	@echo "... src/GB_LogData.i"
	@echo "... src/GB_LogData.s"
	@echo "... src/GB_Logger.o"
	@echo "... src/GB_Logger.i"
	@echo "... src/GB_Logger.s"
	@echo "... src/GB_SimpleStrategy.o"
	@echo "... src/GB_SimpleStrategy.i"
	@echo "... src/GB_SimpleStrategy.s"
	@echo "... src/GodBot.o"
	@echo "... src/GodBot.i"
	@echo "... src/GodBot.s"
	@echo "... src/Kline.o"
	@echo "... src/Kline.i"
	@echo "... src/Kline.s"
	@echo "... src/base_api.o"
	@echo "... src/base_api.i"
	@echo "... src/base_api.s"
	@echo "... src/binance_api.o"
	@echo "... src/binance_api.i"
	@echo "... src/binance_api.s"
	@echo "... src/curl_object.o"
	@echo "... src/curl_object.i"
	@echo "... src/curl_object.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

